// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8C8F8LTVF83dYRbh9NH18sr9mPT6-xE0',
    appId: '1:309040460950:web:9d9e2b06ca3ec3f783beb7',
    messagingSenderId: '309040460950',
    projectId: 'noteq-apps',
    authDomain: 'noteq-apps.firebaseapp.com',
    storageBucket: 'noteq-apps.appspot.com',
    measurementId: 'G-PLRXWQEE51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgP7zJgQM99brFFS29IlPjyNwox-RRn-0',
    appId: '1:309040460950:android:0ea932acac1aa52083beb7',
    messagingSenderId: '309040460950',
    projectId: 'noteq-apps',
    storageBucket: 'noteq-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVwNFv-Gc58IT12rw7qPDSpL8G_D3EPX4',
    appId: '1:309040460950:ios:5f343a439b8e232b83beb7',
    messagingSenderId: '309040460950',
    projectId: 'noteq-apps',
    storageBucket: 'noteq-apps.appspot.com',
    iosBundleId: 'com.example.noteq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVwNFv-Gc58IT12rw7qPDSpL8G_D3EPX4',
    appId: '1:309040460950:ios:a846317ca502616f83beb7',
    messagingSenderId: '309040460950',
    projectId: 'noteq-apps',
    storageBucket: 'noteq-apps.appspot.com',
    iosBundleId: 'com.example.noteq.RunnerTests',
  );
}
